#***************************************************************************
#
#  (C) 2000 ECCMagic
#
#  Java package makefile.
#
#***************************************************************************

#***************************************************************************
#
#  Section 1. Package description.
#
#  o PACKAGE     - The complete package name.
#  o PACKAGE_LOC - Same as PACKAGE but with "/"s instead of "."s.
#  o SOURCE      - List of the source files. Remember .java extension.
#  o NAIN        - Class containing main function if any
#
#***************************************************************************

PACKAGE     = jcdsee.imagebrowser
PACKAGE_LOC = jcdsee/imagebrowser


SOURCE = \
	ImageBrowser.java \
	ImageInfo.java \
	ImageLoaderListener.java \
	ImageLoaderThread.java \
	ImageSelectionEvent.java \
	ImageSelectionListener.java \
	InfoButton.java \
	ScrollPaneWrapLayout.java \
	ThumbPanel.java \

MAIN   =


#***************************************************************************
#
#  Section 2. Common part of makefile
#
#***************************************************************************

include $(JAVA_TOP)/make/Makerules

