#***************************************************************************
#
#  (C) 2000 ECCMagic
#
#  Java package makefile.
#
#***************************************************************************

#***************************************************************************
#
#  Section 1. Package description.
#
#  o PACKAGE     - The complete package name.
#  o PACKAGE_LOC - Same as PACKAGE but with "/"s instead of "."s.
#  o SOURCE      - List of the source files. Remember .java extension.
#  o NAIN        - Class containing main function if any
#
#***************************************************************************

PACKAGE     = jcdsee.folderbrowser
PACKAGE_LOC = jcdsee/folderbrowser


SOURCE = \
	DirectoryEvent.java \
	DirectoryEventListener.java \
	FolderBrowser.java \

MAIN   =


#***************************************************************************
#
#  Section 2. Common part of makefile
#
#***************************************************************************

include $(JAVA_TOP)/make/Makerules

